#!/bin/sh

for dir in `fndr`
do
  if [ -f $dir/Makefile ]
  then
    co -l $dir/Makefile
  fi
done

dir=`fndr | head -1`

cd $dir

make deps

for dir in `fndr`
do
  if [ -f $dir/Makefile ]
  then
    ci -u -m"make deps done" $dir/Makefile
  fi
done

