/* This file is automatically generated (by scanGROUPS.awk)
** DO NOT EDIT BELOW!
*/

#include "externVars.h"

extern void (*eval)();

int convert(inF)
FILE *inF;
{
  int length = 0;
  DBUG_ENTER("convert");

  switch(ID) {
  case MINDEX_HEAP_ALLOC: {
    length = MSCAN_HEAP_ALLOC(inF, &HA_SIZE, &HA_ADR, &HA_REF);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_HEAP_FREE: {
    length = MSCAN_HEAP_FREE(inF, &HF_ADR, &HF_REF);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_HEAP_COMPACT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_DESC_ALLOC: {
    length = MSCAN_DESC_ALLOC(inF, &DA_ADR);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_DESC_FREE: {
    length = MSCAN_DESC_FREE(inF, &DF_ADR);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_STACK_PUSH: {
    length = MSCAN_STACK_PUSH(inF, PS_STACK);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_STACK_POP: {
    length = MSCAN_STACK_POP(inF, PP_STACK);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_STACK_SEG_FREE: {
    length = MSCAN_STACK_SEG_FREE(inF, SSF_STACK);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_STACK_SEG_ALLOC: {
    length = MSCAN_STACK_SEG_ALLOC(inF, SSA_STACK);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DIST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DISTB: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_DISTSTACKS: {
    length = MSCAN_PROC_DISTSTACKS(inF, &PDS_SIZE);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_DIST: {
    length = MSCAN_PROC_DIST(inF, &PD_NEXT_PROC, &PD_SIZE);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_NODIST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_CREATE: {
    length = MSCAN_PROC_CREATE(inF, &PC_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_TERMINATE: {
    length = MSCAN_PROC_TERMINATE(inF, &PT_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_DISTEND: {
    length = MSCAN_PROC_DISTEND(inF, &PD_RET_PID, &PD_RET_PROC);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_SLEEP: {
    length = MSCAN_PROC_SLEEP(inF, &PS_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_RUN: {
    length = MSCAN_PROC_RUN(inF, &PR_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_PROC_WAKEUP: {
    length = MSCAN_PROC_WAKEUP(inF, &PW_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_SEND_BEGIN: {
    length = MSCAN_SEND_BEGIN(inF, S_TYPE, &S_TARGET_PROC, &S_TARGET_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_SEND_END: {
    length = MSCAN_SEND_END(inF, &S_SIZE);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_RECEIVE_BEGIN: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_RECEIVE_END: {
    length = MSCAN_RECEIVE_END(inF, R_TYPE, &R_FROM_PROC, &R_FROM_PID, &R_SIZE, &R_FOR_PID);
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_W: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSHC_W: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_AW: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_AW0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOVE_AW: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DELTA1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DELTA2: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DELTA3: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DELTA4: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_ADD: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_SUB: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MUL: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DIV: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOD: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_EQ: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_NE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_LT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_LE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_NEG: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_NOT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_OR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_AND: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_XOR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JFALSE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTRUE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JCOND: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSHRET: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETA: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETA0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETA1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETAQ: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETAQ0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BETAQ1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FREE_A: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FREE1_A: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTF: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTM: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTP: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTC: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKGCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKBCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKCCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKSCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKDCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKAP: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_APPLY: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_CASE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_WHEN: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GUARD: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_BODY: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_NOMATCH: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DUPARG: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_LSEL: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_CONS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FCONS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FIRST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_REST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_EXT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKILIST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKLIST: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSHH: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_DISTEND: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_WAIT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_POPH: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_R: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSHC_R: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOVE_WR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSHRET_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FREE_R: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FREE1_R: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTT: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTM_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_RTC_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMA: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMA0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMA1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMAQ: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMAQ0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMAQ1: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL0_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAIL1_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ0_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_JTAILQ1_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_TW: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_TW0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_TR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_TR0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_AR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_PUSH_AR0: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOVE_TW: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOVE_TR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MOVE_AR: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMABETA: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_FREESW_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_GAMMACASE: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKGACLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_POPFREE_T: {
    (*eval)();
    DBUG_RETURN(length);
  }

  case MINDEX_COUNT_MKGSCLOS: {
    (*eval)();
    DBUG_RETURN(length);
  }

  }
  DBUG_PRINT("convert", ("Unknown id: %d", ID));
  DBUG_RETURN(-1);
}
