/* This file is automatically generated (by scanGROUPS.awk)
** DO NOT EDIT BELOW!
*/

extern double TIME;
int PROCESS;
extern short PROCESSOR, ID;

/* HEAP_ALLOC */
extern int HA_SIZE;
extern int HA_ADR;
extern int HA_REF;

/* HEAP_FREE */
extern int HF_ADR;
extern int HF_REF;

/* HEAP_COMPACT */

/* DESC_ALLOC */
extern int DA_ADR;

/* DESC_FREE */
extern int DF_ADR;

/* STACK_PUSH */
extern char PS_STACK[100];

/* STACK_POP */
extern char PP_STACK[100];

/* STACK_SEG_FREE */
extern char SSF_STACK[100];

/* STACK_SEG_ALLOC */
extern char SSA_STACK[100];

/* COUNT_DIST */

/* COUNT_DISTB */

/* PROC_DISTSTACKS */
extern int PDS_SIZE;

/* PROC_DIST */
extern int PD_NEXT_PROC;
extern int PD_SIZE;

/* PROC_NODIST */

/* PROC_CREATE */
extern int PC_PID;

/* PROC_TERMINATE */
extern int PT_PID;

/* PROC_DISTEND */
extern int PD_RET_PID;
extern int PD_RET_PROC;

/* PROC_SLEEP */
extern int PS_PID;

/* PROC_RUN */
extern int PR_PID;

/* PROC_WAKEUP */
extern int PW_PID;

/* SEND_BEGIN */
extern char S_TYPE[100];
extern int S_TARGET_PROC;
extern int S_TARGET_PID;

/* SEND_END */
extern int S_SIZE;

/* RECEIVE_BEGIN */

/* RECEIVE_END */
extern char R_TYPE[100];
extern int R_FROM_PROC;
extern int R_FROM_PID;
extern int R_SIZE;
extern int R_FOR_PID;

/* COUNT_PUSH_W */

/* COUNT_PUSHC_W */

/* COUNT_PUSH_AW */

/* COUNT_PUSH_AW0 */

/* COUNT_MOVE_AW */

/* COUNT_DELTA1 */

/* COUNT_DELTA2 */

/* COUNT_DELTA3 */

/* COUNT_DELTA4 */

/* COUNT_ADD */

/* COUNT_SUB */

/* COUNT_MUL */

/* COUNT_DIV */

/* COUNT_MOD */

/* COUNT_EQ */

/* COUNT_NE */

/* COUNT_LT */

/* COUNT_LE */

/* COUNT_GT */

/* COUNT_GE */

/* COUNT_NEG */

/* COUNT_NOT */

/* COUNT_OR */

/* COUNT_AND */

/* COUNT_XOR */

/* COUNT_JFALSE */

/* COUNT_JTRUE */

/* COUNT_JCOND */

/* COUNT_PUSHRET */

/* COUNT_BETA */

/* COUNT_BETA0 */

/* COUNT_BETA1 */

/* COUNT_JTAIL */

/* COUNT_JTAIL0 */

/* COUNT_JTAIL1 */

/* COUNT_BETAQ */

/* COUNT_BETAQ0 */

/* COUNT_BETAQ1 */

/* COUNT_JTAILQ */

/* COUNT_JTAILQ0 */

/* COUNT_JTAILQ1 */

/* COUNT_FREE_A */

/* COUNT_FREE1_A */

/* COUNT_RTF */

/* COUNT_RTM */

/* COUNT_RTP */

/* COUNT_RTC */

/* COUNT_RTS */

/* COUNT_MKGCLOS */

/* COUNT_MKBCLOS */

/* COUNT_MKCCLOS */

/* COUNT_MKSCLOS */

/* COUNT_MKDCLOS */

/* COUNT_MKAP */

/* COUNT_APPLY */

/* COUNT_CASE */

/* COUNT_WHEN */

/* COUNT_GUARD */

/* COUNT_BODY */

/* COUNT_NOMATCH */

/* COUNT_DUPARG */

/* COUNT_LSEL */

/* COUNT_CONS */

/* COUNT_FCONS */

/* COUNT_FIRST */

/* COUNT_REST */

/* COUNT_EXT */

/* COUNT_MKILIST */

/* COUNT_MKLIST */

/* COUNT_PUSHH */

/* COUNT_DISTEND */

/* COUNT_WAIT */

/* COUNT_POPH */

/* COUNT_PUSH_R */

/* COUNT_PUSHC_R */

/* COUNT_MOVE_WR */

/* COUNT_PUSHRET_T */

/* COUNT_FREE_R */

/* COUNT_FREE1_R */

/* COUNT_RTT */

/* COUNT_RTM_T */

/* COUNT_RTC_T */

/* COUNT_GAMMA */

/* COUNT_GAMMA0 */

/* COUNT_GAMMA1 */

/* COUNT_GAMMAQ */

/* COUNT_GAMMAQ0 */

/* COUNT_GAMMAQ1 */

/* COUNT_JTAIL_T */

/* COUNT_JTAIL0_T */

/* COUNT_JTAIL1_T */

/* COUNT_JTAILQ_T */

/* COUNT_JTAILQ0_T */

/* COUNT_JTAILQ1_T */

/* COUNT_PUSH_TW */

/* COUNT_PUSH_TW0 */

/* COUNT_PUSH_TR */

/* COUNT_PUSH_TR0 */

/* COUNT_PUSH_AR */

/* COUNT_PUSH_AR0 */

/* COUNT_MOVE_TW */

/* COUNT_MOVE_TR */

/* COUNT_MOVE_AR */

/* COUNT_GAMMABETA */

/* COUNT_FREESW_T */

/* COUNT_GAMMACASE */

/* COUNT_MKGACLOS */

/* COUNT_POPFREE_T */

/* COUNT_MKGSCLOS */

