/* This file is automatically generated (by scanGROUPS.awk)
** DO NOT EDIT BELOW!
*/

short id2Index(id)
char *id;
{
  DBUG_ENTER("id2index");

  if(!strcmp(id, "HEAP_ALLOC")) {
    DBUG_RETURN(MINDEX_HEAP_ALLOC);
  }

  if(!strcmp(id, "HEAP_FREE")) {
    DBUG_RETURN(MINDEX_HEAP_FREE);
  }

  if(!strcmp(id, "HEAP_COMPACT")) {
    DBUG_RETURN(MINDEX_HEAP_COMPACT);
  }

  if(!strcmp(id, "DESC_ALLOC")) {
    DBUG_RETURN(MINDEX_DESC_ALLOC);
  }

  if(!strcmp(id, "DESC_FREE")) {
    DBUG_RETURN(MINDEX_DESC_FREE);
  }

  if(!strcmp(id, "STACK_PUSH")) {
    DBUG_RETURN(MINDEX_STACK_PUSH);
  }

  if(!strcmp(id, "STACK_POP")) {
    DBUG_RETURN(MINDEX_STACK_POP);
  }

  if(!strcmp(id, "STACK_SEG_FREE")) {
    DBUG_RETURN(MINDEX_STACK_SEG_FREE);
  }

  if(!strcmp(id, "STACK_SEG_ALLOC")) {
    DBUG_RETURN(MINDEX_STACK_SEG_ALLOC);
  }

  if(!strcmp(id, "COUNT_DIST")) {
    DBUG_RETURN(MINDEX_COUNT_DIST);
  }

  if(!strcmp(id, "COUNT_DISTB")) {
    DBUG_RETURN(MINDEX_COUNT_DISTB);
  }

  if(!strcmp(id, "PROC_DISTSTACKS")) {
    DBUG_RETURN(MINDEX_PROC_DISTSTACKS);
  }

  if(!strcmp(id, "PROC_DIST")) {
    DBUG_RETURN(MINDEX_PROC_DIST);
  }

  if(!strcmp(id, "PROC_NODIST")) {
    DBUG_RETURN(MINDEX_PROC_NODIST);
  }

  if(!strcmp(id, "PROC_CREATE")) {
    DBUG_RETURN(MINDEX_PROC_CREATE);
  }

  if(!strcmp(id, "PROC_TERMINATE")) {
    DBUG_RETURN(MINDEX_PROC_TERMINATE);
  }

  if(!strcmp(id, "PROC_DISTEND")) {
    DBUG_RETURN(MINDEX_PROC_DISTEND);
  }

  if(!strcmp(id, "PROC_SLEEP")) {
    DBUG_RETURN(MINDEX_PROC_SLEEP);
  }

  if(!strcmp(id, "PROC_RUN")) {
    DBUG_RETURN(MINDEX_PROC_RUN);
  }

  if(!strcmp(id, "PROC_WAKEUP")) {
    DBUG_RETURN(MINDEX_PROC_WAKEUP);
  }

  if(!strcmp(id, "SEND_BEGIN")) {
    DBUG_RETURN(MINDEX_SEND_BEGIN);
  }

  if(!strcmp(id, "SEND_END")) {
    DBUG_RETURN(MINDEX_SEND_END);
  }

  if(!strcmp(id, "RECEIVE_BEGIN")) {
    DBUG_RETURN(MINDEX_RECEIVE_BEGIN);
  }

  if(!strcmp(id, "RECEIVE_END")) {
    DBUG_RETURN(MINDEX_RECEIVE_END);
  }

  if(!strcmp(id, "COUNT_PUSH_W")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_W);
  }

  if(!strcmp(id, "COUNT_PUSHC_W")) {
    DBUG_RETURN(MINDEX_COUNT_PUSHC_W);
  }

  if(!strcmp(id, "COUNT_PUSH_AW")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_AW);
  }

  if(!strcmp(id, "COUNT_PUSH_AW0")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_AW0);
  }

  if(!strcmp(id, "COUNT_MOVE_AW")) {
    DBUG_RETURN(MINDEX_COUNT_MOVE_AW);
  }

  if(!strcmp(id, "COUNT_DELTA1")) {
    DBUG_RETURN(MINDEX_COUNT_DELTA1);
  }

  if(!strcmp(id, "COUNT_DELTA2")) {
    DBUG_RETURN(MINDEX_COUNT_DELTA2);
  }

  if(!strcmp(id, "COUNT_DELTA3")) {
    DBUG_RETURN(MINDEX_COUNT_DELTA3);
  }

  if(!strcmp(id, "COUNT_DELTA4")) {
    DBUG_RETURN(MINDEX_COUNT_DELTA4);
  }

  if(!strcmp(id, "COUNT_ADD")) {
    DBUG_RETURN(MINDEX_COUNT_ADD);
  }

  if(!strcmp(id, "COUNT_SUB")) {
    DBUG_RETURN(MINDEX_COUNT_SUB);
  }

  if(!strcmp(id, "COUNT_MUL")) {
    DBUG_RETURN(MINDEX_COUNT_MUL);
  }

  if(!strcmp(id, "COUNT_DIV")) {
    DBUG_RETURN(MINDEX_COUNT_DIV);
  }

  if(!strcmp(id, "COUNT_MOD")) {
    DBUG_RETURN(MINDEX_COUNT_MOD);
  }

  if(!strcmp(id, "COUNT_EQ")) {
    DBUG_RETURN(MINDEX_COUNT_EQ);
  }

  if(!strcmp(id, "COUNT_NE")) {
    DBUG_RETURN(MINDEX_COUNT_NE);
  }

  if(!strcmp(id, "COUNT_LT")) {
    DBUG_RETURN(MINDEX_COUNT_LT);
  }

  if(!strcmp(id, "COUNT_LE")) {
    DBUG_RETURN(MINDEX_COUNT_LE);
  }

  if(!strcmp(id, "COUNT_GT")) {
    DBUG_RETURN(MINDEX_COUNT_GT);
  }

  if(!strcmp(id, "COUNT_GE")) {
    DBUG_RETURN(MINDEX_COUNT_GE);
  }

  if(!strcmp(id, "COUNT_NEG")) {
    DBUG_RETURN(MINDEX_COUNT_NEG);
  }

  if(!strcmp(id, "COUNT_NOT")) {
    DBUG_RETURN(MINDEX_COUNT_NOT);
  }

  if(!strcmp(id, "COUNT_OR")) {
    DBUG_RETURN(MINDEX_COUNT_OR);
  }

  if(!strcmp(id, "COUNT_AND")) {
    DBUG_RETURN(MINDEX_COUNT_AND);
  }

  if(!strcmp(id, "COUNT_XOR")) {
    DBUG_RETURN(MINDEX_COUNT_XOR);
  }

  if(!strcmp(id, "COUNT_JFALSE")) {
    DBUG_RETURN(MINDEX_COUNT_JFALSE);
  }

  if(!strcmp(id, "COUNT_JTRUE")) {
    DBUG_RETURN(MINDEX_COUNT_JTRUE);
  }

  if(!strcmp(id, "COUNT_JCOND")) {
    DBUG_RETURN(MINDEX_COUNT_JCOND);
  }

  if(!strcmp(id, "COUNT_PUSHRET")) {
    DBUG_RETURN(MINDEX_COUNT_PUSHRET);
  }

  if(!strcmp(id, "COUNT_BETA")) {
    DBUG_RETURN(MINDEX_COUNT_BETA);
  }

  if(!strcmp(id, "COUNT_BETA0")) {
    DBUG_RETURN(MINDEX_COUNT_BETA0);
  }

  if(!strcmp(id, "COUNT_BETA1")) {
    DBUG_RETURN(MINDEX_COUNT_BETA1);
  }

  if(!strcmp(id, "COUNT_JTAIL")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL);
  }

  if(!strcmp(id, "COUNT_JTAIL0")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL0);
  }

  if(!strcmp(id, "COUNT_JTAIL1")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL1);
  }

  if(!strcmp(id, "COUNT_BETAQ")) {
    DBUG_RETURN(MINDEX_COUNT_BETAQ);
  }

  if(!strcmp(id, "COUNT_BETAQ0")) {
    DBUG_RETURN(MINDEX_COUNT_BETAQ0);
  }

  if(!strcmp(id, "COUNT_BETAQ1")) {
    DBUG_RETURN(MINDEX_COUNT_BETAQ1);
  }

  if(!strcmp(id, "COUNT_JTAILQ")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ);
  }

  if(!strcmp(id, "COUNT_JTAILQ0")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ0);
  }

  if(!strcmp(id, "COUNT_JTAILQ1")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ1);
  }

  if(!strcmp(id, "COUNT_FREE_A")) {
    DBUG_RETURN(MINDEX_COUNT_FREE_A);
  }

  if(!strcmp(id, "COUNT_FREE1_A")) {
    DBUG_RETURN(MINDEX_COUNT_FREE1_A);
  }

  if(!strcmp(id, "COUNT_RTF")) {
    DBUG_RETURN(MINDEX_COUNT_RTF);
  }

  if(!strcmp(id, "COUNT_RTM")) {
    DBUG_RETURN(MINDEX_COUNT_RTM);
  }

  if(!strcmp(id, "COUNT_RTP")) {
    DBUG_RETURN(MINDEX_COUNT_RTP);
  }

  if(!strcmp(id, "COUNT_RTC")) {
    DBUG_RETURN(MINDEX_COUNT_RTC);
  }

  if(!strcmp(id, "COUNT_RTS")) {
    DBUG_RETURN(MINDEX_COUNT_RTS);
  }

  if(!strcmp(id, "COUNT_MKGCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKGCLOS);
  }

  if(!strcmp(id, "COUNT_MKBCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKBCLOS);
  }

  if(!strcmp(id, "COUNT_MKCCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKCCLOS);
  }

  if(!strcmp(id, "COUNT_MKSCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKSCLOS);
  }

  if(!strcmp(id, "COUNT_MKDCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKDCLOS);
  }

  if(!strcmp(id, "COUNT_MKAP")) {
    DBUG_RETURN(MINDEX_COUNT_MKAP);
  }

  if(!strcmp(id, "COUNT_APPLY")) {
    DBUG_RETURN(MINDEX_COUNT_APPLY);
  }

  if(!strcmp(id, "COUNT_CASE")) {
    DBUG_RETURN(MINDEX_COUNT_CASE);
  }

  if(!strcmp(id, "COUNT_WHEN")) {
    DBUG_RETURN(MINDEX_COUNT_WHEN);
  }

  if(!strcmp(id, "COUNT_GUARD")) {
    DBUG_RETURN(MINDEX_COUNT_GUARD);
  }

  if(!strcmp(id, "COUNT_BODY")) {
    DBUG_RETURN(MINDEX_COUNT_BODY);
  }

  if(!strcmp(id, "COUNT_NOMATCH")) {
    DBUG_RETURN(MINDEX_COUNT_NOMATCH);
  }

  if(!strcmp(id, "COUNT_DUPARG")) {
    DBUG_RETURN(MINDEX_COUNT_DUPARG);
  }

  if(!strcmp(id, "COUNT_LSEL")) {
    DBUG_RETURN(MINDEX_COUNT_LSEL);
  }

  if(!strcmp(id, "COUNT_CONS")) {
    DBUG_RETURN(MINDEX_COUNT_CONS);
  }

  if(!strcmp(id, "COUNT_FCONS")) {
    DBUG_RETURN(MINDEX_COUNT_FCONS);
  }

  if(!strcmp(id, "COUNT_FIRST")) {
    DBUG_RETURN(MINDEX_COUNT_FIRST);
  }

  if(!strcmp(id, "COUNT_REST")) {
    DBUG_RETURN(MINDEX_COUNT_REST);
  }

  if(!strcmp(id, "COUNT_EXT")) {
    DBUG_RETURN(MINDEX_COUNT_EXT);
  }

  if(!strcmp(id, "COUNT_MKILIST")) {
    DBUG_RETURN(MINDEX_COUNT_MKILIST);
  }

  if(!strcmp(id, "COUNT_MKLIST")) {
    DBUG_RETURN(MINDEX_COUNT_MKLIST);
  }

  if(!strcmp(id, "COUNT_PUSHH")) {
    DBUG_RETURN(MINDEX_COUNT_PUSHH);
  }

  if(!strcmp(id, "COUNT_DISTEND")) {
    DBUG_RETURN(MINDEX_COUNT_DISTEND);
  }

  if(!strcmp(id, "COUNT_WAIT")) {
    DBUG_RETURN(MINDEX_COUNT_WAIT);
  }

  if(!strcmp(id, "COUNT_POPH")) {
    DBUG_RETURN(MINDEX_COUNT_POPH);
  }

  if(!strcmp(id, "COUNT_PUSH_R")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_R);
  }

  if(!strcmp(id, "COUNT_PUSHC_R")) {
    DBUG_RETURN(MINDEX_COUNT_PUSHC_R);
  }

  if(!strcmp(id, "COUNT_MOVE_WR")) {
    DBUG_RETURN(MINDEX_COUNT_MOVE_WR);
  }

  if(!strcmp(id, "COUNT_PUSHRET_T")) {
    DBUG_RETURN(MINDEX_COUNT_PUSHRET_T);
  }

  if(!strcmp(id, "COUNT_FREE_R")) {
    DBUG_RETURN(MINDEX_COUNT_FREE_R);
  }

  if(!strcmp(id, "COUNT_FREE1_R")) {
    DBUG_RETURN(MINDEX_COUNT_FREE1_R);
  }

  if(!strcmp(id, "COUNT_RTT")) {
    DBUG_RETURN(MINDEX_COUNT_RTT);
  }

  if(!strcmp(id, "COUNT_RTM_T")) {
    DBUG_RETURN(MINDEX_COUNT_RTM_T);
  }

  if(!strcmp(id, "COUNT_RTC_T")) {
    DBUG_RETURN(MINDEX_COUNT_RTC_T);
  }

  if(!strcmp(id, "COUNT_GAMMA")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMA);
  }

  if(!strcmp(id, "COUNT_GAMMA0")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMA0);
  }

  if(!strcmp(id, "COUNT_GAMMA1")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMA1);
  }

  if(!strcmp(id, "COUNT_GAMMAQ")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMAQ);
  }

  if(!strcmp(id, "COUNT_GAMMAQ0")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMAQ0);
  }

  if(!strcmp(id, "COUNT_GAMMAQ1")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMAQ1);
  }

  if(!strcmp(id, "COUNT_JTAIL_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL_T);
  }

  if(!strcmp(id, "COUNT_JTAIL0_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL0_T);
  }

  if(!strcmp(id, "COUNT_JTAIL1_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAIL1_T);
  }

  if(!strcmp(id, "COUNT_JTAILQ_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ_T);
  }

  if(!strcmp(id, "COUNT_JTAILQ0_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ0_T);
  }

  if(!strcmp(id, "COUNT_JTAILQ1_T")) {
    DBUG_RETURN(MINDEX_COUNT_JTAILQ1_T);
  }

  if(!strcmp(id, "COUNT_PUSH_TW")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_TW);
  }

  if(!strcmp(id, "COUNT_PUSH_TW0")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_TW0);
  }

  if(!strcmp(id, "COUNT_PUSH_TR")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_TR);
  }

  if(!strcmp(id, "COUNT_PUSH_TR0")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_TR0);
  }

  if(!strcmp(id, "COUNT_PUSH_AR")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_AR);
  }

  if(!strcmp(id, "COUNT_PUSH_AR0")) {
    DBUG_RETURN(MINDEX_COUNT_PUSH_AR0);
  }

  if(!strcmp(id, "COUNT_MOVE_TW")) {
    DBUG_RETURN(MINDEX_COUNT_MOVE_TW);
  }

  if(!strcmp(id, "COUNT_MOVE_TR")) {
    DBUG_RETURN(MINDEX_COUNT_MOVE_TR);
  }

  if(!strcmp(id, "COUNT_MOVE_AR")) {
    DBUG_RETURN(MINDEX_COUNT_MOVE_AR);
  }

  if(!strcmp(id, "COUNT_GAMMABETA")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMABETA);
  }

  if(!strcmp(id, "COUNT_FREESW_T")) {
    DBUG_RETURN(MINDEX_COUNT_FREESW_T);
  }

  if(!strcmp(id, "COUNT_GAMMACASE")) {
    DBUG_RETURN(MINDEX_COUNT_GAMMACASE);
  }

  if(!strcmp(id, "COUNT_MKGACLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKGACLOS);
  }

  if(!strcmp(id, "COUNT_POPFREE_T")) {
    DBUG_RETURN(MINDEX_COUNT_POPFREE_T);
  }

  if(!strcmp(id, "COUNT_MKGSCLOS")) {
    DBUG_RETURN(MINDEX_COUNT_MKGSCLOS);
  }

  DBUG_RETURN(0);
}
