#ifndef WI_ms_heap_array_layout_h
#define WI_ms_heap_array_layout_h
/* $Id$
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for tb on Wed Sep  8 10:29:04 1993
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xaw/AsciiText.h>
#include <X11/Xukc/ScrollList.h>
#include <X11/Shell.h>
#include <X11/Xukc/Toggle.h>
#include <X11/Xukc/Med3Menu.h>
#include <X11/Xukc/Arrow.h>
#include <X11/Xukc/Scrollbar.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Command.h>
#include <X11/Xukc/Passive.h>
#include <X11/Xukc/Layout.h>

struct w_connections {
	Widget *layout;
	Widget *w1;
	Widget *w2;
	Positioning pos;
};

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_ms_heap_array_classes[] = {
	{ &asciiTextWidgetClass, "asciiTextWidgetClass" },
	{ &ukcScrListWidgetClass, "ukcScrListWidgetClass" },
	{ &ukcToggleWidgetClass, "ukcToggleWidgetClass" },
	{ &ukcMed3MenuWidgetClass, "ukcMed3MenuWidgetClass" },
	{ &ukcArrowWidgetClass, "ukcArrowWidgetClass" },
	{ &ukcScrollbarWidgetClass, "ukcScrollbarWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcCommandWidgetClass, "ukcCommandWidgetClass" },
	{ &ukcPassiveWidgetClass, "ukcPassiveWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
};

struct w_constructors WI_ms_heap_array_constructors[] = {
	{ XtCreateTransientShell, "XtCreateTransientShell" },
};

/* WIDGET ID. VARIABLES */

Widget WI_ms_heap_array;
Widget  WI_ms_heap_array_box;
Widget   WI_ms_heap_array_graphic_box;
Widget    WI_ms_heap_array_graphic_area;
Widget   WI_ms_command_panel_box;
Widget    WI_ms_command_panel_exit;
Widget   WI_ms_heap_array_control_box;
Widget    WI_ms_cursor_panel_box;
Widget     WI_ms_cursor_panel_label_x;
Widget     WI_ms_cursor_panel_label_y;
Widget     WI_ms_cursor_panel_show_x;
Widget     WI_ms_cursor_panel_show_y;
Widget    WI_ms_position_panel_box;
Widget     WI_ms_position_panel_label_line;
Widget     WI_ms_position_panel_label_frame;
Widget     WI_ms_position_panel_label_time;
Widget     WI_ms_position_panel_show_line;
Widget     WI_ms_position_panel_enter_frame;
Widget     WI_ms_position_panel_enter_time;
Widget    WI_ms_control_panel_box;
Widget     WI_ms_control_panel_go_to_start;
Widget     WI_ms_control_panel_play_backward;
Widget     WI_ms_control_panel_skip_backward;
Widget     WI_ms_control_panel_stop;
Widget     WI_ms_control_panel_skip_forward;
Widget     WI_ms_control_panel_play_forward;
Widget     WI_ms_control_panel_go_to_end;
Widget    WI_ms_speed_panel_box;
Widget     WI_ms_speed_panel_label_delay;
Widget     WI_ms_speed_panel_label_rate;
Widget     WI_ms_speed_panel_enter_delay;
Widget     WI_ms_speed_panel_enter_rate;
Widget     WI_ms_speed_panel_scroll_delay;
Widget     WI_ms_speed_panel_scroll_left_delay;
Widget     WI_ms_speed_panel_scroll_right_delay;
Widget     WI_ms_speed_panel_scroll_rate;
Widget     WI_ms_speed_panel_scroll_left_rate;
Widget     WI_ms_speed_panel_scroll_right_rate;
Widget   WI_ms_script_panel_box;
Widget    WI_ms_script_panel_label;
Widget    WI_ms_script_panel_label_path;
Widget    WI_ms_script_panel_enter_path;
Widget    WI_ms_script_panel_label_name;
Widget    WI_ms_script_panel_enter_name;
Widget    WI_ms_script_panel_run;
Widget    WI_ms_script_panel_browse;
Widget    WI_ms_script_panel_save;
Widget    WI_ms_script_panel_edit;
Widget   WI_ms_file_panel_box;
Widget    WI_ms_file_panel_label;
Widget    WI_ms_file_panel_label_path;
Widget    WI_ms_file_panel_enter_path;
Widget    WI_ms_file_panel_label_name;
Widget    WI_ms_file_panel_enter_name;
Widget    WI_ms_file_panel_browse;
Widget    WI_ms_file_panel_filter;
Widget   WI_ms_progress_box;
Widget    WI_ms_progress_label;
Widget    WI_ms_progress_bar;
Widget   WI_ms_display_panel_box;
Widget    WI_ms_display_panel_label;
Widget    WI_ms_display_panel_label_title;
Widget    WI_ms_display_panel_enter_title;
Widget    WI_ms_display_panel_clear;
Widget    WI_ms_display_panel_caching;
Widget    WI_ms_display_panel_stacking;
Widget    WI_ms_display_panel_separation;
Widget    WI_ms_display_panel_fragmentation;
Widget    WI_ms_display_panel_save;
Widget    WI_ms_display_panel_print;
Widget  WI_ms_file_browser;
Widget   WI_my_requester_box;
Widget    WI_my_requester_select_box;
Widget     WI_my_requester_select_enter_mask;
Widget     WI_my_requester_select_label;
Widget     WI_my_requester_select_label_mask;
Widget     WI_my_requester_select_label_path;
Widget     WI_my_requester_select_enter_path;
Widget     WI_my_requester_select_enter_file;
Widget     WI_my_requester_select_label_file;
Widget     WI_my_requester_select_scroll;
Widget    WI_my_requester_command_box;
Widget     WI_my_requester_command_cancel;
Widget     WI_my_requester_command_o_k;
Widget  WI_editor;
Widget   WI_editor_box;
Widget    WI_editor_edit_window;
Widget    WI_editor_close;
Widget  WI_ms_requester;
Widget   WI_ms_requester_box;
Widget    WI_ms_requester_title;
Widget     WI_ms_requester_title1;
Widget     WI_ms_requester_title2;
Widget     WI_ms_requester_title3;
Widget    WI_ms_requester_action;
Widget     WI_ms_requester_action_o_k;
Widget     WI_ms_requester_action_cancel;
Widget     WI_ms_requester_action_help;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_ms_heap_array_bind_list[] = {
	{ &WI_ms_heap_array_box, "*msHeapArrayBox" },
	{ &WI_ms_heap_array_graphic_box, "*msHeapArrayGraphicBox" },
	{ &WI_ms_heap_array_graphic_area, "*msHeapArrayGraphicArea" },
	{ &WI_ms_command_panel_box, "*msCommandPanelBox" },
	{ &WI_ms_command_panel_exit, "*msCommandPanelExit" },
	{ &WI_ms_heap_array_control_box, "*msHeapArrayControlBox" },
	{ &WI_ms_cursor_panel_box, "*msCursorPanelBox" },
	{ &WI_ms_cursor_panel_label_x, "*msCursorPanelLabelX" },
	{ &WI_ms_cursor_panel_label_y, "*msCursorPanelLabelY" },
	{ &WI_ms_cursor_panel_show_x, "*msCursorPanelShowX" },
	{ &WI_ms_cursor_panel_show_y, "*msCursorPanelShowY" },
	{ &WI_ms_position_panel_box, "*msPositionPanelBox" },
	{ &WI_ms_position_panel_label_line, "*msPositionPanelLabelLine" },
	{ &WI_ms_position_panel_label_frame, "*msPositionPanelLabelFrame" },
	{ &WI_ms_position_panel_label_time, "*msPositionPanelLabelTime" },
	{ &WI_ms_position_panel_show_line, "*msPositionPanelShowLine" },
	{ &WI_ms_position_panel_enter_frame, "*msPositionPanelEnterFrame" },
	{ &WI_ms_position_panel_enter_time, "*msPositionPanelEnterTime" },
	{ &WI_ms_control_panel_box, "*msControlPanelBox" },
	{ &WI_ms_control_panel_go_to_start, "*msControlPanelGoToStart" },
	{ &WI_ms_control_panel_play_backward, "*msControlPanelPlayBackward" },
	{ &WI_ms_control_panel_skip_backward, "*msControlPanelSkipBackward" },
	{ &WI_ms_control_panel_stop, "*msControlPanelStop" },
	{ &WI_ms_control_panel_skip_forward, "*msControlPanelSkipForward" },
	{ &WI_ms_control_panel_play_forward, "*msControlPanelPlayForward" },
	{ &WI_ms_control_panel_go_to_end, "*msControlPanelGoToEnd" },
	{ &WI_ms_speed_panel_box, "*msSpeedPanelBox" },
	{ &WI_ms_speed_panel_label_delay, "*msSpeedPanelLabelDelay" },
	{ &WI_ms_speed_panel_label_rate, "*msSpeedPanelLabelRate" },
	{ &WI_ms_speed_panel_enter_delay, "*msSpeedPanelEnterDelay" },
	{ &WI_ms_speed_panel_enter_rate, "*msSpeedPanelEnterRate" },
	{ &WI_ms_speed_panel_scroll_delay, "*msSpeedPanelScrollDelay" },
	{ &WI_ms_speed_panel_scroll_left_delay, "*msSpeedPanelScrollLeftDelay" },
	{ &WI_ms_speed_panel_scroll_right_delay, "*msSpeedPanelScrollRightDelay" },
	{ &WI_ms_speed_panel_scroll_rate, "*msSpeedPanelScrollRate" },
	{ &WI_ms_speed_panel_scroll_left_rate, "*msSpeedPanelScrollLeftRate" },
	{ &WI_ms_speed_panel_scroll_right_rate, "*msSpeedPanelScrollRightRate" },
	{ &WI_ms_script_panel_box, "*msScriptPanelBox" },
	{ &WI_ms_script_panel_label, "*msScriptPanelLabel" },
	{ &WI_ms_script_panel_label_path, "*msScriptPanelLabelPath" },
	{ &WI_ms_script_panel_enter_path, "*msScriptPanelEnterPath" },
	{ &WI_ms_script_panel_label_name, "*msScriptPanelLabelName" },
	{ &WI_ms_script_panel_enter_name, "*msScriptPanelEnterName" },
	{ &WI_ms_script_panel_run, "*msScriptPanelRun" },
	{ &WI_ms_script_panel_browse, "*msScriptPanelBrowse" },
	{ &WI_ms_script_panel_save, "*msScriptPanelSave" },
	{ &WI_ms_script_panel_edit, "*msScriptPanelEdit" },
	{ &WI_ms_file_panel_box, "*msFilePanelBox" },
	{ &WI_ms_file_panel_label, "*msFilePanelLabel" },
	{ &WI_ms_file_panel_label_path, "*msFilePanelLabelPath" },
	{ &WI_ms_file_panel_enter_path, "*msFilePanelEnterPath" },
	{ &WI_ms_file_panel_label_name, "*msFilePanelLabelName" },
	{ &WI_ms_file_panel_enter_name, "*msFilePanelEnterName" },
	{ &WI_ms_file_panel_browse, "*msFilePanelBrowse" },
	{ &WI_ms_file_panel_filter, "*msFilePanelFilter" },
	{ &WI_ms_progress_box, "*msProgressBox" },
	{ &WI_ms_progress_label, "*msProgressLabel" },
	{ &WI_ms_progress_bar, "*msProgressBar" },
	{ &WI_ms_display_panel_box, "*msDisplayPanelBox" },
	{ &WI_ms_display_panel_label, "*msDisplayPanelLabel" },
	{ &WI_ms_display_panel_label_title, "*msDisplayPanelLabelTitle" },
	{ &WI_ms_display_panel_enter_title, "*msDisplayPanelEnterTitle" },
	{ &WI_ms_display_panel_clear, "*msDisplayPanelClear" },
	{ &WI_ms_display_panel_caching, "*msDisplayPanelCaching" },
	{ &WI_ms_display_panel_stacking, "*msDisplayPanelStacking" },
	{ &WI_ms_display_panel_separation, "*msDisplayPanelSeparation" },
	{ &WI_ms_display_panel_fragmentation, "*msDisplayPanelFragmentation" },
	{ &WI_ms_display_panel_save, "*msDisplayPanelSave" },
	{ &WI_ms_display_panel_print, "*msDisplayPanelPrint" },
	{ &WI_ms_file_browser, "*msFileBrowser" },
	{ &WI_my_requester_box, "*myRequesterBox" },
	{ &WI_my_requester_select_box, "*myRequesterSelectBox" },
	{ &WI_my_requester_select_enter_mask, "*myRequesterSelectEnterMask" },
	{ &WI_my_requester_select_label, "*myRequesterSelectLabel" },
	{ &WI_my_requester_select_label_mask, "*myRequesterSelectLabelMask" },
	{ &WI_my_requester_select_label_path, "*myRequesterSelectLabelPath" },
	{ &WI_my_requester_select_enter_path, "*myRequesterSelectEnterPath" },
	{ &WI_my_requester_select_enter_file, "*myRequesterSelectEnterFile" },
	{ &WI_my_requester_select_label_file, "*myRequesterSelectLabelFile" },
	{ &WI_my_requester_select_scroll, "*myRequesterSelectScroll" },
	{ &WI_my_requester_command_box, "*myRequesterCommandBox" },
	{ &WI_my_requester_command_cancel, "*myRequesterCommandCancel" },
	{ &WI_my_requester_command_o_k, "*myRequesterCommandOK" },
	{ &WI_editor, "*editor" },
	{ &WI_editor_box, "*editorBox" },
	{ &WI_editor_edit_window, "*editorEditWindow" },
	{ &WI_editor_close, "*editorClose" },
	{ &WI_ms_requester, "*msRequester" },
	{ &WI_ms_requester_box, "*msRequesterBox" },
	{ &WI_ms_requester_title, "*msRequesterTitle" },
	{ &WI_ms_requester_title1, "*msRequesterTitle1" },
	{ &WI_ms_requester_title2, "*msRequesterTitle2" },
	{ &WI_ms_requester_title3, "*msRequesterTitle3" },
	{ &WI_ms_requester_action, "*msRequesterAction" },
	{ &WI_ms_requester_action_o_k, "*msRequesterActionOK" },
	{ &WI_ms_requester_action_cancel, "*msRequesterActionCancel" },
	{ &WI_ms_requester_action_help, "*msRequesterActionHelp" },
};


/* CALLBACK REGISTRATION LIST */

String WI_ms_heap_array_callback_names[] = {
	"msSpeedPanelSetRate",
	"msSpeedPanelSetDelay",
	"msSpeedPanelIncreaseRate",
	"msSpeedPanelIncreaseDelay",
	"msSpeedPanelEnterRate",
	"msSpeedPanelEnterDelay",
	"msSpeedPanelDecreaseRate",
	"msSpeedPanelDecreaseDelay",
	"msScriptPanelSave",
	"msScriptPanelRun",
	"msScriptPanelEnterPath",
	"msScriptPanelEnterName",
	"msScriptPanelEdit",
	"msScriptPanelBrowse",
	"msPositionPanelEnterTime",
	"msPositionPanelEnterFrame",
	"msHistoryPanelSetLevel",
	"msHistoryPanelIncreaseLevel",
	"msHistoryPanelEnterLevel",
	"msHistoryPanelDecreaseLevel",
	"msFuturePanelSetLevel",
	"msFuturePanelIncreaseLevel",
	"msFuturePanelEnterLevel",
	"msFuturePanelDecreaseLevel",
	"msFilePanelEnterPath",
	"msFilePanelEnterName",
	"msFilePanelBrowse",
	"msFileBrowserUpdate",
	"msFileBrowserSelectFile",
	"msFileBrowserInitialize",
	"msFileBrowserAccept",
	"msDisplayPanelSetTitle",
	"msDisplayPanelSetStyleText",
	"msDisplayPanelSetStyleNone",
	"msDisplayPanelSetStyleColor",
	"msDisplayPanelSetStyle",
	"msDisplayPanelSetStacking",
	"msDisplayPanelSetSeparation",
	"msDisplayPanelSetFragmentation",
	"msDisplayPanelSetCaching",
	"msDisplayPanelSave",
	"msDisplayPanelRedrawe",
	"msDisplayPanelRedraw",
	"msDisplayPanelPrint",
	"msDisplayPanelClear",
	"msControlPanelStop",
	"msControlPanelStepForward",
	"msControlPanelStepBackward",
	"msControlPanelSkipForward",
	"msControlPanelSkipBackward",
	"msControlPanelPlayForward",
	"msControlPanelPlayBackward",
	"msControlPanelPlayBackward",
	"msControlPanelGoToStart",
	"msControlPanelGoToEnd",
	"msBarChartZoomZoomOut",
	"msBarChartZoomYSetMin",
	"msBarChartZoomYSetMax",
	"msBarChartZoomXSetMin",
	"msBarChartZoomXSetMax",
	"msBarChartZoomShowAll",
	"msBarChartStorePreferences",
	"msBarChartStop",
	"msBarChartStepForward",
	"msBarChartStepBackward",
	"msBarChartSetRate",
	"msBarChartSetDelay",
	"msBarChartPlayForward",
	"msBarChartPlayBackward",
	"msBarChartGoToStart",
	"msBarChartGoToEnd",
	"msBarChartFileCall",
	"msBarChartExitHook",
	"msBarChartDisplayYSetTitle",
	"msBarChartDisplayYSetSubGrid",
	"msBarChartDisplayYSetMin",
	"msBarChartDisplayYSetMax",
	"msBarChartDisplayYSetLog",
	"msBarChartDisplayYSetLinear",
	"msBarChartDisplayYSetGrid",
	"msBarChartDisplayXSetTitle",
	"msBarChartDisplayXSetSubGrid",
	"msBarChartDisplayXSetMin",
	"msBarChartDisplayXSetMax",
	"msBarChartDisplayXSetLog",
	"msBarChartDisplayXSetLinear",
	"msBarChartDisplayXSetGrid",
	"msBarChartDisplaySetTitle",
	"msBarChartDisplaySave",
	"msBarChartDisplayPrint",
	"msBarChartDisplayLegend",
	"msBarChartDisplayClear",
	"mcControlPanelSkipBackward",
	"exitHook",
};

/* ACTION REGISTRATION LIST */

String WI_ms_heap_array_action_names[] = {
	"msProcArrayMousePosition",
	"msProcArrayClickRight",
	"msProcArrayClickMiddle",
	"msProcArrayClickLeft",
	"msHeapArrayMousePosition",
	"msHeapArrayClickRight",
	"msHeapArrayClickMiddle",
	"msHeapArrayClickLeft",
	"msBarChartResizePlotter",
};


/* LAYOUT CONNECTIONS */

/* widget connection list for UKCLayout widgets */
struct w_connections WI_ms_heap_array_widget_connections[] = {
	{ &WI_my_requester_select_box, &WI_my_requester_select_label, &WI_my_requester_select_box, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_mask, &WI_my_requester_select_label, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_path, &WI_my_requester_select_enter_mask, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_enter_path, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_mask, &WI_my_requester_select_label, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_path, &WI_my_requester_select_label_mask, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_label_path, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_file, &WI_my_requester_select_scroll, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_file, &WI_my_requester_select_scroll, vertical_above },
	{ &WI_my_requester_command_box, &WI_my_requester_command_cancel, &WI_my_requester_command_box, vertical_above },
	{ &WI_my_requester_command_box, &WI_my_requester_command_o_k, &WI_my_requester_command_box, vertical_above },
	{ &WI_my_requester_box, &WI_my_requester_command_box, &WI_my_requester_select_box, vertical_above },
	{ &WI_my_requester_box, &WI_my_requester_select_box, &WI_my_requester_box, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_mask, &WI_my_requester_select_label_mask, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_path, &WI_my_requester_select_label_path, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_mask, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_path, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_file, &WI_my_requester_select_label_file, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_file, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_command_box, &WI_my_requester_command_o_k, &WI_my_requester_command_cancel, horizontal_before },
	{ &WI_my_requester_command_box, &WI_my_requester_command_cancel, &WI_my_requester_command_box, horizontal_before },
	{ &WI_my_requester_box, &WI_my_requester_command_box, &WI_my_requester_box, horizontal_before },
	{ &WI_my_requester_box, &WI_my_requester_select_box, &WI_my_requester_box, horizontal_before },
	{ &WI_ms_heap_array_control_box, &WI_ms_cursor_panel_box, &WI_ms_heap_array_control_box, vertical_above },
	{ &WI_ms_heap_array_control_box, &WI_ms_position_panel_box, &WI_ms_heap_array_control_box, vertical_above },
	{ &WI_ms_heap_array_control_box, &WI_ms_control_panel_box, &WI_ms_heap_array_control_box, vertical_above },
	{ &WI_ms_heap_array_control_box, &WI_ms_speed_panel_box, &WI_ms_heap_array_control_box, vertical_above },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_label_x, &WI_ms_cursor_panel_box, vertical_above },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_label_y, &WI_ms_cursor_panel_label_x, vertical_above },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_show_y, &WI_ms_cursor_panel_show_x, vertical_above },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_show_x, &WI_ms_cursor_panel_box, vertical_above },
	{ &WI_ms_heap_array_control_box, &WI_ms_cursor_panel_box, &WI_ms_heap_array_control_box, horizontal_before },
	{ &WI_ms_heap_array_control_box, &WI_ms_position_panel_box, &WI_ms_cursor_panel_box, horizontal_before },
	{ &WI_ms_heap_array_control_box, &WI_ms_control_panel_box, &WI_ms_position_panel_box, horizontal_before },
	{ &WI_ms_heap_array_control_box, &WI_ms_speed_panel_box, &WI_ms_control_panel_box, horizontal_before },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_show_x, &WI_ms_cursor_panel_label_x, horizontal_before },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_show_y, &WI_ms_cursor_panel_label_y, horizontal_before },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_label_frame, &WI_ms_position_panel_label_line, vertical_above },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_label_time, &WI_ms_position_panel_label_frame, vertical_above },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_show_line, &WI_ms_position_panel_box, vertical_above },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_enter_frame, &WI_ms_position_panel_show_line, vertical_above },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_enter_time, &WI_ms_position_panel_enter_frame, vertical_above },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_show_line, &WI_ms_position_panel_label_line, horizontal_before },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_enter_frame, &WI_ms_position_panel_label_frame, horizontal_before },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_label_frame, &WI_ms_position_panel_box, horizontal_before },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_enter_time, &WI_ms_position_panel_label_time, horizontal_before },
	{ &WI_ms_position_panel_box, &WI_ms_position_panel_label_time, &WI_ms_position_panel_box, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_go_to_start, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_play_backward, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_skip_backward, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_stop, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_skip_forward, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_play_forward, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_go_to_end, &WI_ms_control_panel_box, vertical_above },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_go_to_end, &WI_ms_control_panel_play_forward, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_play_forward, &WI_ms_control_panel_skip_forward, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_skip_forward, &WI_ms_control_panel_stop, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_stop, &WI_ms_control_panel_skip_backward, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_skip_backward, &WI_ms_control_panel_play_backward, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_play_backward, &WI_ms_control_panel_go_to_start, horizontal_before },
	{ &WI_ms_control_panel_box, &WI_ms_control_panel_go_to_start, &WI_ms_control_panel_box, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_label_delay, &WI_ms_speed_panel_box, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_label_rate, &WI_ms_speed_panel_label_delay, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_enter_delay, &WI_ms_speed_panel_box, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_enter_rate, &WI_ms_speed_panel_enter_delay, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_left_delay, &WI_ms_speed_panel_box, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_delay, &WI_ms_speed_panel_box, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_right_delay, &WI_ms_speed_panel_box, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_left_rate, &WI_ms_speed_panel_scroll_left_delay, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_rate, &WI_ms_speed_panel_scroll_delay, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_right_rate, &WI_ms_speed_panel_scroll_right_delay, vertical_above },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_right_delay, &WI_ms_speed_panel_scroll_delay, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_right_rate, &WI_ms_speed_panel_scroll_rate, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_delay, &WI_ms_speed_panel_scroll_left_delay, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_rate, &WI_ms_speed_panel_scroll_left_rate, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_left_delay, &WI_ms_speed_panel_enter_delay, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_scroll_left_rate, &WI_ms_speed_panel_enter_rate, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_enter_delay, &WI_ms_speed_panel_label_delay, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_enter_rate, &WI_ms_speed_panel_label_rate, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_label_delay, &WI_ms_speed_panel_box, horizontal_before },
	{ &WI_ms_speed_panel_box, &WI_ms_speed_panel_label_rate, &WI_ms_speed_panel_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_heap_array_graphic_box, &WI_ms_heap_array_box, vertical_above },
	{ &WI_ms_heap_array_box, &WI_ms_command_panel_box, &WI_ms_heap_array_control_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_heap_array_graphic_box, &WI_ms_heap_array_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_heap_array_control_box, &WI_ms_heap_array_box, horizontal_before },
	{ &WI_ms_command_panel_box, &WI_ms_command_panel_exit, &WI_ms_command_panel_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_script_panel_box, &WI_ms_heap_array_graphic_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_enter_path, &WI_ms_script_panel_label, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_enter_name, &WI_ms_script_panel_enter_path, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label_path, &WI_ms_script_panel_label, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label_name, &WI_ms_script_panel_label_path, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_enter_path, &WI_ms_script_panel_label_path, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label_path, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_enter_name, &WI_ms_script_panel_label_name, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label_name, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_save, &WI_ms_script_panel_browse, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_script_panel_box, &WI_ms_file_panel_box, vertical_above },
	{ &WI_ms_heap_array_box, &WI_ms_file_panel_box, &WI_ms_heap_array_graphic_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_browse, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_filter, &WI_ms_file_panel_browse, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_browse, &WI_ms_file_panel_enter_name, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_enter_name, &WI_ms_file_panel_enter_path, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_enter_path, &WI_ms_file_panel_label, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label_path, &WI_ms_file_panel_label, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label_name, &WI_ms_file_panel_label_path, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_browse, &WI_ms_file_panel_label_name, vertical_above },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_enter_path, &WI_ms_file_panel_label_path, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_enter_name, &WI_ms_file_panel_label_name, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label, &WI_ms_file_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label_name, &WI_ms_file_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label_path, &WI_ms_file_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_browse, &WI_ms_file_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_filter, &WI_ms_file_panel_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_browse, &WI_ms_script_panel_enter_name, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_browse, &WI_ms_script_panel_label_name, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_save, &WI_ms_script_panel_browse, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_edit, &WI_ms_script_panel_browse, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_run, &WI_ms_script_panel_edit, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_run, &WI_ms_script_panel_save, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_edit, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_save, &WI_ms_script_panel_edit, horizontal_before },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_run, &WI_ms_script_panel_box, horizontal_before },
	{ &WI_ms_file_panel_box, &WI_ms_file_panel_label, &WI_ms_file_panel_box, vertical_above },
	{ &WI_editor_box, &WI_editor_close, &WI_editor_edit_window, vertical_above },
	{ &WI_editor_box, &WI_editor_edit_window, &WI_editor_box, vertical_above },
	{ &WI_editor_box, &WI_editor_edit_window, &WI_editor_box, horizontal_before },
	{ &WI_editor_box, &WI_editor_close, &WI_editor_box, horizontal_before },
	{ &WI_ms_heap_array_graphic_box, &WI_ms_heap_array_graphic_area, &WI_ms_heap_array_graphic_box, vertical_above },
	{ &WI_ms_heap_array_graphic_box, &WI_ms_heap_array_graphic_area, &WI_ms_heap_array_graphic_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_progress_box, &WI_ms_heap_array_graphic_box, vertical_above },
	{ &WI_ms_heap_array_box, &WI_ms_heap_array_control_box, &WI_ms_progress_box, vertical_above },
	{ &WI_ms_progress_box, &WI_ms_progress_label, &WI_ms_progress_box, horizontal_before },
	{ &WI_ms_progress_box, &WI_ms_progress_label, &WI_ms_progress_box, vertical_above },
	{ &WI_ms_cursor_panel_box, &WI_ms_cursor_panel_label_y, &WI_ms_cursor_panel_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_display_panel_box, &WI_ms_script_panel_box, vertical_above },
	{ &WI_ms_heap_array_box, &WI_ms_display_panel_box, &WI_ms_heap_array_graphic_box, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_label, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_label_title, &WI_ms_display_panel_label, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_enter_title, &WI_ms_display_panel_label, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_enter_title, &WI_ms_display_panel_label_title, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_label_title, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_clear, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_progress_box, &WI_ms_progress_bar, &WI_ms_progress_label, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_progress_box, &WI_ms_heap_array_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_file_panel_box, &WI_ms_heap_array_box, vertical_above },
	{ &WI_ms_script_panel_box, &WI_ms_script_panel_label, &WI_ms_script_panel_box, vertical_above },
	{ &WI_ms_command_panel_box, &WI_ms_command_panel_exit, &WI_ms_command_panel_box, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_stacking, &WI_ms_display_panel_caching, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_caching, &WI_ms_display_panel_enter_title, vertical_above },
	{ &WI_ms_heap_array_box, &WI_ms_command_panel_box, &WI_ms_heap_array_graphic_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_command_panel_box, &WI_ms_progress_box, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_clear, &WI_ms_display_panel_separation, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_caching, &WI_ms_display_panel_label_title, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_separation, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_fragmentation, &WI_ms_display_panel_stacking, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_separation, &WI_ms_display_panel_fragmentation, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_fragmentation, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_o_k, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_action, &WI_ms_requester_action_cancel, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_action, &WI_ms_requester_action_help, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_action, &WI_ms_requester_action_o_k, &WI_ms_requester_action_cancel, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_cancel, &WI_ms_requester_action_help, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_help, &WI_ms_requester_action, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_action, &WI_ms_requester_box, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_action, &WI_ms_requester_title, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title3, &WI_ms_requester_title2, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title2, &WI_ms_requester_title1, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title1, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title2, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title3, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_title, &WI_ms_requester_box, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title1, &WI_ms_requester_title, vertical_above },
	{ &WI_ms_requester_box, &WI_ms_requester_title, &WI_ms_requester_box, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_print, &WI_ms_display_panel_clear, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_save, &WI_ms_display_panel_clear, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_print, &WI_ms_display_panel_save, horizontal_before },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_save, &WI_ms_display_panel_box, horizontal_before },
	{ &WI_ms_heap_array_box, &WI_ms_command_panel_box, &WI_ms_display_panel_box, vertical_above },
	{ &WI_ms_display_panel_box, &WI_ms_display_panel_label, &WI_ms_display_panel_box, vertical_above },
};

/* END */
#endif /* WI_ms_heap_array_layout_h */
