#ifndef WI_ms_main_layout_h
#define WI_ms_main_layout_h
/* $Id$
 *
 * X Toolkit program layout header file.
 * This file contains all the definitions of the static parts
 * of the user interface.
 */

/*
 * This file was generated by the DIRT interface editor
 *	Author: Richard Hesketh / rlh2@ukc.ac.uk
 *	Version: 1.3 (Wc) of July 1990
 *
 * Generated for tb on Thu Jul 29 14:26:34 1993
 */

#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xukc/ScrollList.h>
#include <X11/Shell.h>
#include <X11/Xukc/Toggle.h>
#include <X11/Xukc/Command.h>
#include <X11/Xukc/Med3Menu.h>
#include <X11/Xukc/Label.h>
#include <X11/Xukc/Layout.h>

struct w_connections {
	Widget *layout;
	Widget *w1;
	Widget *w2;
	Positioning pos;
};

/* WIDGET/OBJECT class registration list */

struct w_classes {
	WidgetClass *class;
	String class_name;
};

/* WIDGET/OBJECT constructor registration list */

struct w_constructors {
	Widget (*constructor)();
	String constructor_name;
};

struct w_classes WI_ms_main_classes[] = {
	{ &ukcScrListWidgetClass, "ukcScrListWidgetClass" },
	{ &ukcToggleWidgetClass, "ukcToggleWidgetClass" },
	{ &ukcCommandWidgetClass, "ukcCommandWidgetClass" },
	{ &ukcMed3MenuWidgetClass, "ukcMed3MenuWidgetClass" },
	{ &ukcLabelWidgetClass, "ukcLabelWidgetClass" },
	{ &ukcLayoutWidgetClass, "ukcLayoutWidgetClass" },
};

struct w_constructors WI_ms_main_constructors[] = {
	{ XtCreateTransientShell, "XtCreateTransientShell" },
};

/* WIDGET ID. VARIABLES */

Widget WI_ms_main;
Widget  WI_ms_main_box;
Widget   WI_ms_main_module_box;
Widget    WI_ms_main_module_label;
Widget    WI_ms_main_module_menu;
Widget   WI_ms_main_file_box;
Widget    WI_ms_main_file_label;
Widget    WI_ms_main_file_enter_path;
Widget    WI_ms_main_file_enter_name;
Widget    WI_ms_main_file_label_path;
Widget    WI_ms_main_file_label_name;
Widget    WI_ms_main_file_browse;
Widget    WI_ms_main_file_filter_menu;
Widget   WI_ms_main_reduma_box;
Widget    WI_ms_main_reduma_label;
Widget    WI_ms_main_reduma_init_menu;
Widget    WI_ms_main_reduma_call;
Widget   WI_ms_main_preferences_box;
Widget    WI_ms_main_preferences_label;
Widget    WI_ms_main_preferences_toggle;
Widget    WI_ms_main_preferences_store;
Widget   WI_ms_main_quit_box;
Widget    WI_ms_main_quit;
Widget   WI_ms_file_browser;
Widget    WI_my_requester_box;
Widget     WI_my_requester_select_box;
Widget      WI_my_requester_select_enter_mask;
Widget      WI_my_requester_select_label;
Widget      WI_my_requester_select_label_mask;
Widget      WI_my_requester_select_label_path;
Widget      WI_my_requester_select_enter_path;
Widget      WI_my_requester_select_enter_file;
Widget      WI_my_requester_select_label_file;
Widget      WI_my_requester_select_scroll;
Widget     WI_my_requester_command_box;
Widget      WI_my_requester_command_o_k;
Widget      WI_my_requester_command_cancel;
Widget   WI_ms_requester;
Widget    WI_ms_requester_box;
Widget     WI_ms_requester_title;
Widget      WI_ms_requester_title1;
Widget      WI_ms_requester_title2;
Widget      WI_ms_requester_title3;
Widget     WI_ms_requester_action;
Widget      WI_ms_requester_action_o_k;
Widget      WI_ms_requester_action_cancel;
Widget      WI_ms_requester_action_help;


/* RUNTIME BINDING STRUCTURE */

struct w_bind_list {
	Widget *w;
	String str;
};

struct w_bind_list WI_ms_main_bind_list[] = {
	{ &WI_ms_main_box, "*msMainBox" },
	{ &WI_ms_main_module_box, "*msMainModuleBox" },
	{ &WI_ms_main_module_label, "*msMainModuleLabel" },
	{ &WI_ms_main_module_menu, "*msMainModuleMenu" },
	{ &WI_ms_main_file_box, "*msMainFileBox" },
	{ &WI_ms_main_file_label, "*msMainFileLabel" },
	{ &WI_ms_main_file_enter_path, "*msMainFileEnterPath" },
	{ &WI_ms_main_file_enter_name, "*msMainFileEnterName" },
	{ &WI_ms_main_file_label_path, "*msMainFileLabelPath" },
	{ &WI_ms_main_file_label_name, "*msMainFileLabelName" },
	{ &WI_ms_main_file_browse, "*msMainFileBrowse" },
	{ &WI_ms_main_file_filter_menu, "*msMainFileFilterMenu" },
	{ &WI_ms_main_reduma_box, "*msMainRedumaBox" },
	{ &WI_ms_main_reduma_label, "*msMainRedumaLabel" },
	{ &WI_ms_main_reduma_init_menu, "*msMainRedumaInitMenu" },
	{ &WI_ms_main_reduma_call, "*msMainRedumaCall" },
	{ &WI_ms_main_preferences_box, "*msMainPreferencesBox" },
	{ &WI_ms_main_preferences_label, "*msMainPreferencesLabel" },
	{ &WI_ms_main_preferences_toggle, "*msMainPreferencesToggle" },
	{ &WI_ms_main_preferences_store, "*msMainPreferencesStore" },
	{ &WI_ms_main_quit_box, "*msMainQuitBox" },
	{ &WI_ms_main_quit, "*msMainQuit" },
	{ &WI_ms_file_browser, "*msFileBrowser" },
	{ &WI_my_requester_box, "*myRequesterBox" },
	{ &WI_my_requester_select_box, "*myRequesterSelectBox" },
	{ &WI_my_requester_select_enter_mask, "*myRequesterSelectEnterMask" },
	{ &WI_my_requester_select_label, "*myRequesterSelectLabel" },
	{ &WI_my_requester_select_label_mask, "*myRequesterSelectLabelMask" },
	{ &WI_my_requester_select_label_path, "*myRequesterSelectLabelPath" },
	{ &WI_my_requester_select_enter_path, "*myRequesterSelectEnterPath" },
	{ &WI_my_requester_select_enter_file, "*myRequesterSelectEnterFile" },
	{ &WI_my_requester_select_label_file, "*myRequesterSelectLabelFile" },
	{ &WI_my_requester_select_scroll, "*myRequesterSelectScroll" },
	{ &WI_my_requester_command_box, "*myRequesterCommandBox" },
	{ &WI_my_requester_command_o_k, "*myRequesterCommandOK" },
	{ &WI_my_requester_command_cancel, "*myRequesterCommandCancel" },
	{ &WI_ms_requester, "*msRequester" },
	{ &WI_ms_requester_box, "*msRequesterBox" },
	{ &WI_ms_requester_title, "*msRequesterTitle" },
	{ &WI_ms_requester_title1, "*msRequesterTitle1" },
	{ &WI_ms_requester_title2, "*msRequesterTitle2" },
	{ &WI_ms_requester_title3, "*msRequesterTitle3" },
	{ &WI_ms_requester_action, "*msRequesterAction" },
	{ &WI_ms_requester_action_o_k, "*msRequesterActionOK" },
	{ &WI_ms_requester_action_cancel, "*msRequesterActionCancel" },
	{ &WI_ms_requester_action_help, "*msRequesterActionHelp" },
};


/* CALLBACK REGISTRATION LIST */

String WI_ms_main_callback_names[] = {
	"msMainStorePreferences",
	"msMainRedumaCall",
	"msMainFileCall",
	"msMainFileBrowse",
	"msMainExitHook",
	"msFileBrowserUpdate",
	"msFileBrowserSelectFile",
	"msFileBrowserInitialize",
	"msFileBrowserAccept",
};

/* ACTION REGISTRATION LIST */

String WI_ms_main_action_names[] = {
	"msMainModuleBind",
};


/* LAYOUT CONNECTIONS */

/* widget connection list for UKCLayout widgets */
struct w_connections WI_ms_main_widget_connections[] = {
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_mask, &WI_my_requester_select_label, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label, &WI_my_requester_select_box, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_path, &WI_my_requester_select_enter_mask, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_enter_path, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_file, &WI_my_requester_select_scroll, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_label_path, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_path, &WI_my_requester_select_label_mask, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_mask, &WI_my_requester_select_label, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_file, &WI_my_requester_select_scroll, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_mask, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_path, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_scroll, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_label_file, &WI_my_requester_select_box, horizontal_before },
	{ &WI_my_requester_box, &WI_my_requester_select_box, &WI_my_requester_box, horizontal_before },
	{ &WI_my_requester_box, &WI_my_requester_select_box, &WI_my_requester_box, vertical_above },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_mask, &WI_my_requester_select_label_mask, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_path, &WI_my_requester_select_label_path, horizontal_before },
	{ &WI_my_requester_select_box, &WI_my_requester_select_enter_file, &WI_my_requester_select_label_file, horizontal_before },
	{ &WI_my_requester_command_box, &WI_my_requester_command_o_k, &WI_my_requester_command_box, vertical_above },
	{ &WI_my_requester_box, &WI_my_requester_command_box, &WI_my_requester_select_box, vertical_above },
	{ &WI_my_requester_command_box, &WI_my_requester_command_o_k, &WI_my_requester_command_cancel, horizontal_before },
	{ &WI_my_requester_command_box, &WI_my_requester_command_cancel, &WI_my_requester_command_box, horizontal_before },
	{ &WI_my_requester_box, &WI_my_requester_command_box, &WI_my_requester_box, horizontal_before },
	{ &WI_ms_main_module_box, &WI_ms_main_module_label, &WI_ms_main_module_box, vertical_above },
	{ &WI_ms_main_module_box, &WI_ms_main_module_menu, &WI_ms_main_module_label, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_enter_path, &WI_ms_main_file_label, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_enter_name, &WI_ms_main_file_enter_path, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_browse, &WI_ms_main_file_enter_name, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label_path, &WI_ms_main_file_label, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label_name, &WI_ms_main_file_label_path, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_browse, &WI_ms_main_file_label_name, vertical_above },
	{ &WI_ms_main_box, &WI_ms_main_file_box, &WI_ms_main_module_box, vertical_above },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_label, &WI_ms_main_preferences_box, vertical_above },
	{ &WI_ms_main_quit_box, &WI_ms_main_quit, &WI_ms_main_quit_box, vertical_above },
	{ &WI_ms_main_module_box, &WI_ms_main_module_label, &WI_ms_main_module_box, horizontal_before },
	{ &WI_ms_main_module_box, &WI_ms_main_module_menu, &WI_ms_main_module_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label, &WI_ms_main_file_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label_path, &WI_ms_main_file_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label_name, &WI_ms_main_file_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_enter_path, &WI_ms_main_file_label_path, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_enter_name, &WI_ms_main_file_label_name, horizontal_before },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_label, &WI_ms_main_reduma_box, horizontal_before },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_label, &WI_ms_main_preferences_box, horizontal_before },
	{ &WI_ms_main_quit_box, &WI_ms_main_quit, &WI_ms_main_quit_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_module_box, &WI_ms_main_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_file_box, &WI_ms_main_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_reduma_box, &WI_ms_main_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_preferences_box, &WI_ms_main_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_quit_box, &WI_ms_main_box, horizontal_before },
	{ &WI_ms_main_box, &WI_ms_main_reduma_box, &WI_ms_main_file_box, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_filter_menu, &WI_ms_main_file_browse, vertical_above },
	{ &WI_ms_main_file_box, &WI_ms_main_file_label, &WI_ms_main_file_box, vertical_above },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_store, &WI_ms_main_preferences_toggle, horizontal_before },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_store, &WI_ms_main_preferences_label, vertical_above },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_toggle, &WI_ms_main_preferences_label, vertical_above },
	{ &WI_ms_main_box, &WI_ms_main_quit_box, &WI_ms_main_preferences_box, vertical_above },
	{ &WI_ms_main_box, &WI_ms_main_preferences_box, &WI_ms_main_reduma_box, vertical_above },
	{ &WI_ms_main_preferences_box, &WI_ms_main_preferences_toggle, &WI_ms_main_preferences_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_browse, &WI_ms_main_file_box, horizontal_before },
	{ &WI_ms_main_file_box, &WI_ms_main_file_filter_menu, &WI_ms_main_file_box, horizontal_before },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_init_menu, &WI_ms_main_reduma_box, horizontal_before },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_call, &WI_ms_main_reduma_init_menu, vertical_above },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_init_menu, &WI_ms_main_reduma_label, vertical_above },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_call, &WI_ms_main_reduma_box, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_o_k, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_action, &WI_ms_requester_action_cancel, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_action, &WI_ms_requester_action_help, &WI_ms_requester_action, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title3, &WI_ms_requester_title2, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title2, &WI_ms_requester_title1, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title1, &WI_ms_requester_title, vertical_above },
	{ &WI_ms_requester_box, &WI_ms_requester_title, &WI_ms_requester_box, vertical_above },
	{ &WI_ms_requester_title, &WI_ms_requester_title1, &WI_ms_requester_title2, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title3, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title2, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_o_k, &WI_ms_requester_action_cancel, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_cancel, &WI_ms_requester_action_help, horizontal_before },
	{ &WI_ms_requester_action, &WI_ms_requester_action_help, &WI_ms_requester_action, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_title, &WI_ms_requester_box, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_action, &WI_ms_requester_box, horizontal_before },
	{ &WI_ms_requester_title, &WI_ms_requester_title1, &WI_ms_requester_title, horizontal_before },
	{ &WI_ms_requester_box, &WI_ms_requester_action, &WI_ms_requester_title, vertical_above },
	{ &WI_ms_main_box, &WI_ms_main_module_box, &WI_ms_main_box, vertical_above },
	{ &WI_ms_main_reduma_box, &WI_ms_main_reduma_label, &WI_ms_main_reduma_box, vertical_above },
};

/* END */
#endif /* WI_ms_main_layout_h */
