/* This file is automatically generated (by scanGROUPS.awk)
** DO NOT EDIT BELOW!
*/

#include "externVars.h"

void trevnoc()
{
  int dummy;

  DBUG_ENTER("trevnoc");

  switch(ID) {
  case MINDEX_HEAP_ALLOC: {
    dummy = MPRINT_HEAP_ALLOC(outF, HA_SIZE, HA_ADR, HA_REF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_HEAP_FREE: {
    dummy = MPRINT_HEAP_FREE(outF, HF_ADR, HF_REF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_HEAP_COMPACT: {
    dummy = MPRINT_HEAP_COMPACT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_DESC_ALLOC: {
    dummy = MPRINT_DESC_ALLOC(outF, DA_ADR);
    DBUG_VOID_RETURN;
  }

  case MINDEX_DESC_FREE: {
    dummy = MPRINT_DESC_FREE(outF, DF_ADR);
    DBUG_VOID_RETURN;
  }

  case MINDEX_STACK_PUSH: {
    dummy = MPRINT_STACK_PUSH(outF, PS_STACK);
    DBUG_VOID_RETURN;
  }

  case MINDEX_STACK_POP: {
    dummy = MPRINT_STACK_POP(outF, PP_STACK);
    DBUG_VOID_RETURN;
  }

  case MINDEX_STACK_SEG_FREE: {
    dummy = MPRINT_STACK_SEG_FREE(outF, SSF_STACK);
    DBUG_VOID_RETURN;
  }

  case MINDEX_STACK_SEG_ALLOC: {
    dummy = MPRINT_STACK_SEG_ALLOC(outF, SSA_STACK);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DIST: {
    dummy = MPRINT_COUNT_DIST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DISTB: {
    dummy = MPRINT_COUNT_DISTB(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_DISTSTACKS: {
    dummy = MPRINT_PROC_DISTSTACKS(outF, PDS_SIZE);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_DIST: {
    dummy = MPRINT_PROC_DIST(outF, PD_NEXT_PROC, PD_SIZE);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_NODIST: {
    dummy = MPRINT_PROC_NODIST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_CREATE: {
    dummy = MPRINT_PROC_CREATE(outF, PC_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_TERMINATE: {
    dummy = MPRINT_PROC_TERMINATE(outF, PT_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_DISTEND: {
    dummy = MPRINT_PROC_DISTEND(outF, PD_RET_PID, PD_RET_PROC);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_SLEEP: {
    dummy = MPRINT_PROC_SLEEP(outF, PS_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_RUN: {
    dummy = MPRINT_PROC_RUN(outF, PR_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_PROC_WAKEUP: {
    dummy = MPRINT_PROC_WAKEUP(outF, PW_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_SEND_BEGIN: {
    dummy = MPRINT_SEND_BEGIN(outF, S_TYPE, S_TARGET_PROC, S_TARGET_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_SEND_END: {
    dummy = MPRINT_SEND_END(outF, S_SIZE);
    DBUG_VOID_RETURN;
  }

  case MINDEX_RECEIVE_BEGIN: {
    dummy = MPRINT_RECEIVE_BEGIN(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_RECEIVE_END: {
    dummy = MPRINT_RECEIVE_END(outF, R_TYPE, R_FROM_PROC, R_FROM_PID, R_SIZE, R_FOR_PID);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_W: {
    dummy = MPRINT_COUNT_PUSH_W(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSHC_W: {
    dummy = MPRINT_COUNT_PUSHC_W(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_AW: {
    dummy = MPRINT_COUNT_PUSH_AW(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_AW0: {
    dummy = MPRINT_COUNT_PUSH_AW0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOVE_AW: {
    dummy = MPRINT_COUNT_MOVE_AW(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DELTA1: {
    dummy = MPRINT_COUNT_DELTA1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DELTA2: {
    dummy = MPRINT_COUNT_DELTA2(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DELTA3: {
    dummy = MPRINT_COUNT_DELTA3(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DELTA4: {
    dummy = MPRINT_COUNT_DELTA4(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_ADD: {
    dummy = MPRINT_COUNT_ADD(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_SUB: {
    dummy = MPRINT_COUNT_SUB(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MUL: {
    dummy = MPRINT_COUNT_MUL(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DIV: {
    dummy = MPRINT_COUNT_DIV(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOD: {
    dummy = MPRINT_COUNT_MOD(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_EQ: {
    dummy = MPRINT_COUNT_EQ(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_NE: {
    dummy = MPRINT_COUNT_NE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_LT: {
    dummy = MPRINT_COUNT_LT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_LE: {
    dummy = MPRINT_COUNT_LE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GT: {
    dummy = MPRINT_COUNT_GT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GE: {
    dummy = MPRINT_COUNT_GE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_NEG: {
    dummy = MPRINT_COUNT_NEG(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_NOT: {
    dummy = MPRINT_COUNT_NOT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_OR: {
    dummy = MPRINT_COUNT_OR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_AND: {
    dummy = MPRINT_COUNT_AND(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_XOR: {
    dummy = MPRINT_COUNT_XOR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JFALSE: {
    dummy = MPRINT_COUNT_JFALSE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTRUE: {
    dummy = MPRINT_COUNT_JTRUE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JCOND: {
    dummy = MPRINT_COUNT_JCOND(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSHRET: {
    dummy = MPRINT_COUNT_PUSHRET(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETA: {
    dummy = MPRINT_COUNT_BETA(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETA0: {
    dummy = MPRINT_COUNT_BETA0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETA1: {
    dummy = MPRINT_COUNT_BETA1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL: {
    dummy = MPRINT_COUNT_JTAIL(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL0: {
    dummy = MPRINT_COUNT_JTAIL0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL1: {
    dummy = MPRINT_COUNT_JTAIL1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETAQ: {
    dummy = MPRINT_COUNT_BETAQ(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETAQ0: {
    dummy = MPRINT_COUNT_BETAQ0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BETAQ1: {
    dummy = MPRINT_COUNT_BETAQ1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ: {
    dummy = MPRINT_COUNT_JTAILQ(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ0: {
    dummy = MPRINT_COUNT_JTAILQ0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ1: {
    dummy = MPRINT_COUNT_JTAILQ1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FREE_A: {
    dummy = MPRINT_COUNT_FREE_A(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FREE1_A: {
    dummy = MPRINT_COUNT_FREE1_A(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTF: {
    dummy = MPRINT_COUNT_RTF(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTM: {
    dummy = MPRINT_COUNT_RTM(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTP: {
    dummy = MPRINT_COUNT_RTP(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTC: {
    dummy = MPRINT_COUNT_RTC(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTS: {
    dummy = MPRINT_COUNT_RTS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKGCLOS: {
    dummy = MPRINT_COUNT_MKGCLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKBCLOS: {
    dummy = MPRINT_COUNT_MKBCLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKCCLOS: {
    dummy = MPRINT_COUNT_MKCCLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKSCLOS: {
    dummy = MPRINT_COUNT_MKSCLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKDCLOS: {
    dummy = MPRINT_COUNT_MKDCLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKAP: {
    dummy = MPRINT_COUNT_MKAP(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_APPLY: {
    dummy = MPRINT_COUNT_APPLY(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_CASE: {
    dummy = MPRINT_COUNT_CASE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_WHEN: {
    dummy = MPRINT_COUNT_WHEN(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GUARD: {
    dummy = MPRINT_COUNT_GUARD(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_BODY: {
    dummy = MPRINT_COUNT_BODY(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_NOMATCH: {
    dummy = MPRINT_COUNT_NOMATCH(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DUPARG: {
    dummy = MPRINT_COUNT_DUPARG(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_LSEL: {
    dummy = MPRINT_COUNT_LSEL(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_CONS: {
    dummy = MPRINT_COUNT_CONS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FCONS: {
    dummy = MPRINT_COUNT_FCONS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FIRST: {
    dummy = MPRINT_COUNT_FIRST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_REST: {
    dummy = MPRINT_COUNT_REST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_EXT: {
    dummy = MPRINT_COUNT_EXT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKILIST: {
    dummy = MPRINT_COUNT_MKILIST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKLIST: {
    dummy = MPRINT_COUNT_MKLIST(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSHH: {
    dummy = MPRINT_COUNT_PUSHH(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_DISTEND: {
    dummy = MPRINT_COUNT_DISTEND(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_WAIT: {
    dummy = MPRINT_COUNT_WAIT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_POPH: {
    dummy = MPRINT_COUNT_POPH(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_R: {
    dummy = MPRINT_COUNT_PUSH_R(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSHC_R: {
    dummy = MPRINT_COUNT_PUSHC_R(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOVE_WR: {
    dummy = MPRINT_COUNT_MOVE_WR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSHRET_T: {
    dummy = MPRINT_COUNT_PUSHRET_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FREE_R: {
    dummy = MPRINT_COUNT_FREE_R(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FREE1_R: {
    dummy = MPRINT_COUNT_FREE1_R(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTT: {
    dummy = MPRINT_COUNT_RTT(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTM_T: {
    dummy = MPRINT_COUNT_RTM_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_RTC_T: {
    dummy = MPRINT_COUNT_RTC_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMA: {
    dummy = MPRINT_COUNT_GAMMA(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMA0: {
    dummy = MPRINT_COUNT_GAMMA0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMA1: {
    dummy = MPRINT_COUNT_GAMMA1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMAQ: {
    dummy = MPRINT_COUNT_GAMMAQ(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMAQ0: {
    dummy = MPRINT_COUNT_GAMMAQ0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMAQ1: {
    dummy = MPRINT_COUNT_GAMMAQ1(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL_T: {
    dummy = MPRINT_COUNT_JTAIL_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL0_T: {
    dummy = MPRINT_COUNT_JTAIL0_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAIL1_T: {
    dummy = MPRINT_COUNT_JTAIL1_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ_T: {
    dummy = MPRINT_COUNT_JTAILQ_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ0_T: {
    dummy = MPRINT_COUNT_JTAILQ0_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_JTAILQ1_T: {
    dummy = MPRINT_COUNT_JTAILQ1_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_TW: {
    dummy = MPRINT_COUNT_PUSH_TW(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_TW0: {
    dummy = MPRINT_COUNT_PUSH_TW0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_TR: {
    dummy = MPRINT_COUNT_PUSH_TR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_TR0: {
    dummy = MPRINT_COUNT_PUSH_TR0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_AR: {
    dummy = MPRINT_COUNT_PUSH_AR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_PUSH_AR0: {
    dummy = MPRINT_COUNT_PUSH_AR0(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOVE_TW: {
    dummy = MPRINT_COUNT_MOVE_TW(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOVE_TR: {
    dummy = MPRINT_COUNT_MOVE_TR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MOVE_AR: {
    dummy = MPRINT_COUNT_MOVE_AR(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMABETA: {
    dummy = MPRINT_COUNT_GAMMABETA(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_FREESW_T: {
    dummy = MPRINT_COUNT_FREESW_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_GAMMACASE: {
    dummy = MPRINT_COUNT_GAMMACASE(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKGACLOS: {
    dummy = MPRINT_COUNT_MKGACLOS(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_POPFREE_T: {
    dummy = MPRINT_COUNT_POPFREE_T(outF);
    DBUG_VOID_RETURN;
  }

  case MINDEX_COUNT_MKGSCLOS: {
    dummy = MPRINT_COUNT_MKGSCLOS(outF);
    DBUG_VOID_RETURN;
  }

  }
  DBUG_PRINT("trevnoc", ("Unknown id: %d", ID));
  DBUG_VOID_RETURN;
}
